//Component file autogenerated by Create React App Component Generator.
import React from 'react';

const NotFound: React.FC = (): JSX.Element => {	return (<section></section>);	};

export default NotFound;
