//Component file autogenerated by Create React App Component Generator.

import React from 'react';
import { Animated } from 'react-animated-css';
import PersonGridItemStyles from './PersonGridItem.module.scss';

interface PersonGridItemProps {
	person: Person;
}

const PersonGridItem: React.FC<PersonGridItemProps> = (props: PersonGridItemProps): JSX.Element => {
	return (
		<article className={'notification ' + PersonGridItemStyles.notificationResponsive}>
			<Animated isVisible={true} animationIn="fadeIn" animationOut="fadeOut">
				<section>
					<h5 className="title is-5">{props.person.personServiceName}</h5>
					<section>
						<figure className="media-left">
							<p className="image is-64x64">
								<img alt="Foto de la persona" src="https://i.pravatar.cc/128" />
							</p>
						</figure>
						<section>
							<div className="is-capitalized">
								<div className="is-size-6 has-text-weight-semibold">{props.person.personName}</div>
								<p className="is-size-7">{props.person.serviceAchievements}</p>
							</div>
						</section>
					</section>
					<section className={PersonGridItemStyles.personCardActions}>
						<button className="button is-small is-danger">Perfil de servicios</button>
					</section>
				</section>
			</Animated>
		</article>
	);
};

export default PersonGridItem;
