//Component file autogenerated by Create React App Component Generator.
import React from 'react';
import { AuthActions } from '../Auth.reducer';
import SignUpModalStyles from './SignUpModal.module.scss';
import firebase from '../../index';
import 'firebase/auth';
import { Animated } from 'react-animated-css';

interface SignUpModalProps {
	active: boolean;
	toggleModal: React.Dispatch<AuthActions>;
}

const signUpWithFacebook: Function = () => {
	const provider = new firebase.auth.FacebookAuthProvider();
	firebase.auth().useDeviceLanguage();
	firebase.auth().signInWithRedirect(provider);
};

const signUpWithGoogle: Function = () => {
	const provider = new firebase.auth.GoogleAuthProvider();
	firebase.auth().useDeviceLanguage();
	firebase.auth().signInWithRedirect(provider);
};

const SignUpModal: React.FC<SignUpModalProps> = (props: SignUpModalProps): JSX.Element => {
	const modalClasses: string = props.active ? 'modal is-active' : 'modal';
	return (
		<Animated animationOutDuration={1000} animationIn="fadeIn" animationOut="zoomOut" isVisible={props.active}>
			<div className={modalClasses}>
				<div className="modal-card">
					<header className={'modal-card-head ' + SignUpModalStyles.modalHeader}>
						<p className="modal-card-title has-text-danger has-text-weight-semibold">Registro</p>
						<button
							className="delete"
							onClick={() => props.toggleModal(AuthActions.ToggleSignUpModal)}
							aria-label="Cerrar"
						/>
					</header>
					<section className="modal-card-body has-text-danger ">
						<div>
							<div className="field">
								<p className="control has-icons-left has-icons-right">
									<input className="input is-primary" type="text" placeholder="Nombre" />
									<span className="icon is-small is-left">
										<i className="fas fa-user" />
									</span>
								</p>
							</div>
							<div className="field">
								<p className="control has-icons-left has-icons-right">
									<input className="input is-primary" type="email" placeholder="Correo eléctronico" />
									<span className="icon is-small is-left">
										<i className="fas fa-envelope" />
									</span>
								</p>
							</div>
							<div className="field">
								<p className="control has-icons-left">
									<input className="input is-primary" type="password" placeholder="Contraseña" />
									<span className="icon is-small is-left">
										<i className="fas fa-lock" />
									</span>
								</p>
							</div>
						</div>
						<div className={SignUpModalStyles.modalActions}>
							<div>
								<button className={'button is-small is-danger ' + SignUpModalStyles.modalActionItem}>
									Registrarse
								</button>
							</div>
							<div className={SignUpModalStyles.socialConnect}>
								<button onClick={() => signUpWithFacebook()} className="button is-small is-link">
									<i className="fab fa-facebook-f" />
								</button>
								<button onClick={() => signUpWithGoogle()} className="button is-small is-light">
									<i className="fab fa-google has-text-danger" />
								</button>
								<button className="button is-small is-info">
									<i className="fab fa-twitter" />
								</button>
								<button className="button is-small is-dark">
									<i className="fab fa-github-alt" />
								</button>
								<button className="button is-small is-link">
									<i className="fab fa-microsoft" />
								</button>
							</div>
						</div>
					</section>
				</div>
			</div>
		</Animated>
	);
};

export default SignUpModal;
