//Component test file autogenerated by Create React App Component Generator.
import React from 'react';
import ReactDOM from 'react-dom';
import SignUpModal from './SignUpModal';
const document = window.document;
it('renders without crashing', () => {
	const div = document.createElement('<section></section>');
	ReactDOM.render(<SignUpModal />, div);
	ReactDOM.unmountComponentAtNode(div);
});
