//Component file autogenerated by Create React App Component Generator.
import React from 'react';
import { AuthActions } from '../Auth.reducer';

interface LoginModalProps {
	active: boolean;
	toggleModal: React.Dispatch<AuthActions>;
}

const LoginModal: React.FC<LoginModalProps> = (props: LoginModalProps): JSX.Element => {
	const modalClasses: string = props.active ? 'modal is-active' : 'modal';
	return (
		<div className={modalClasses}>
			<div className="modal-card">
				<header className="modal-card-head">
					<p className="modal-card-title">Inicio de sesión</p>
					<button
						onClick={() => props.toggleModal(AuthActions.ToggleLoginModal)}
						className="delete"
						aria-label="Cerrar"
					/>
				</header>
				<section className="modal-card-body">Iniciar sesión</section>
				<footer className="modal-card-foot">
					<button className="button is-success">Save changes</button>
					<button className="button">Cancel</button>
				</footer>
			</div>
		</div>
	);
};

export default LoginModal;
