//Component file autogenerated by Create React App Component Generator.
import React from 'react';
import MainStyles from './Main.module.scss';
import PersonGridItem from './PersonGridItem/PersonGridItem';

const fakePeopleGrid: Person[][] = [
	[
		{
			id: 1,
			personServiceName: 'Carpintero',
			personName: 'Juanito Pérez',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		},
		{
			id: 2,
			personServiceName: 'Mecánico',
			personName: 'Paola Ponce',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		},
		{
			id: 3,
			personServiceName: 'Pintor',
			personName: 'Diego Mondragon',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		},
		{
			id: 4,
			personServiceName: 'Técnico',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		}
	],
	[
		{
			id: 3,
			personServiceName: 'Pintor',
			personName: 'Diego Mondragon',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		},
		{
			id: 4,
			personServiceName: 'Técnico',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		},
		{
			id: 3,
			personServiceName: 'Pintor',
			personName: 'Diego Mondragon',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		},
		{
			id: 4,
			personServiceName: 'Técnico',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		}
	],
	[
		{
			id: 3,
			personServiceName: 'Pintor',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		},
		{
			id: 4,
			personServiceName: 'Técnico',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		}
	],
	[
		{
			id: 5,
			personServiceName: 'Plomero',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		},
		{
			id: 6,
			personServiceName: 'Cocinero',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		}
	],
	[
		{
			id: 7,
			personServiceName: 'Chofer',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		},
		{
			id: 8,
			personServiceName: 'Músico',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		}
	],
	[
		{
			id: 9,
			personServiceName: 'Entrenador',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		},
		{
			id: 10,
			personServiceName: 'Programador',
			personName: 'Nombre de la persona',
			serviceAchievements: 'Nombre de la persona ha atendido a 250 personas más de la ciudad!'
		}
	]
];

interface MainProps {
	updatedSearchTerm?: string;
}

interface MainState {
	peopleGrid: Person[][];
}

const Main: React.FC<MainProps> = (props: MainProps): JSX.Element => {
	const [ peopleGrid, setPeopleGrid ] = React.useState(fakePeopleGrid);

	React.useEffect(
		() => {
			const timeout = setTimeout(() => {
				setPeopleGrid(() => {
					const nextPeopleGrid = fakePeopleGrid.map((peopleColumn: Person[]) => {
						return peopleColumn.filter((person: Person) =>
							person.personServiceName.includes(props.updatedSearchTerm as string)
						);
					});

					return nextPeopleGrid;
				});
			}, 500);
			return () => {
				clearTimeout(timeout);
			};
		},
		[ props.updatedSearchTerm ]
	);

	return (
		<section>
			<section className={'columns Profs-grid ' + MainStyles.peopleGrid}>
				{peopleGrid.map((gridColumn, currentIndex) => {
					if (gridColumn.length > 0) {
						return (
							<section key={currentIndex} className="column is-one-fifth">
								{gridColumn.map((person) => {
									return <PersonGridItem key={person.id} person={person} />;
								})}
							</section>
						);
					}
				})}
			</section>
		</section>
	);
};

export default Main;
