//Component file autogenerated by Create React App Component Generator.
import React from 'react';

const ReachPeopleInfo: React.FC = (): JSX.Element => {
	return <h2>Reach People Info</h2>;
};

export default ReachPeopleInfo;
