//Component file autogenerated by Create React App Component Generator.
import React from 'react';

const Footer: React.FC = (): JSX.Element => {
	return (
		<footer className="footer has-background-danger ">
			<div className="content has-text-left columns">
				<div className="column columns is-1">
					<span className="column">
						<a href="https://facebook.com">
							<i className="fab fa-facebook-f has-text-light" />
						</a>
					</span>
					<span className="column">
						<a href="https://instagram.com">
							<i className="fab fa-instagram has-text-light" />
						</a>
					</span>
					<span className="column">
						<a href="https://twitter.com">
							<i className="fab fa-twitter has-text-light" />
						</a>
					</span>
				</div>
				<a className="column has-text-light is-half" href="/#">
					<strong>Reach People 2019</strong>
				</a>
			</div>
		</footer>
	);
};

export default Footer;
