//Component file autogenerated by Create React App Component Generator.
import React from 'react';
import { AppAction } from '../App.reducer';

interface HeroProps {
	dispatch: React.Dispatch<AppAction>;
}

const Hero: React.FC<HeroProps> = (props: HeroProps): JSX.Element => {
	return (
		<section className="hero is-danger is-bold">
			<div className="hero-body">
				<div className="container">
					<h1 className="title is-1">Reach People</h1>
					<h2 className="subtitle is-5 has-text-weight-semibold">
						Encuentra a personas que ofrecen servicios a los demás de la ciudad.
					</h2>
					<div className="control has-icons-left">
						<span className="icon">
							<i className="fas fa-search" />
						</span>
						<input
							onChange={(event) =>
								props.dispatch({ name: 'UPDATE_SEARCH_TERM', searchTerm: event.target.value })}
							className="input is-medium is-danger"
							type="text"
							placeholder="Estoy buscando un carpintero, pintor, mecánico, artista, músico..."
						/>
					</div>
				</div>
			</div>
		</section>
	);
};

export default Hero;
