//Component file autogenerated by Create React App Component Generator.
import React from 'react';
import { AuthState, AuthActions, authReducer } from './Auth.reducer';
import SignUpModal from './SignUpModal/SignUpModal';
import LoginModal from './LoginModal/LoginModal';

const Auth: React.FC = (): JSX.Element => {
	const [ state, dispatch ]: [AuthState, React.Dispatch<AuthActions>] = React.useReducer(authReducer, {
		activeSignUpModal: false,
		activeLoginModal: false
	});

	return (
		<section>
			<div className="buttons">
				<button onClick={() => dispatch(AuthActions.ToggleSignUpModal)} className="button is-danger">
					<strong>Registrarse</strong>
				</button>
				<button onClick={() => dispatch(AuthActions.ToggleLoginModal)} className="button is-light">
					Iniciar sesión
				</button>
			</div>
			<SignUpModal toggleModal={dispatch} active={state.activeSignUpModal} />
			<LoginModal toggleModal={dispatch} active={state.activeLoginModal} />
		</section>
	);
};

export default Auth;
